### ISSUE TITLE
kubebox and AWS EKS

### ISSUE THREAD

**Issue by jaydeland** [astefanutti/kubebox#32] opened 2019-01-09 19:24 UTC
This might be related to: https://github.com/astefanutti/kubebox/issues/7

I have not been able to login using kubebox when my terminal session is logged into AWS using the aws authenticator.

**Comment by jaydeland** [comment] 2019-01-09 20:30
At first it says Authentication failed for: <URL>

Than I try to use a generated token to login and it says "Unable to verify first certificate"

**Comment by astefanutti** [comment] 2019-01-10 08:21
Ok thanks. So it's likely related to #7. I'll try to test Kubebox on AWS EKS ASAP.

**Comment by jaydeland** [comment] 2019-01-10 14:07
@astefanutti - Thank you!

**Comment by astefanutti** [comment] 2019-01-15 14:24
I've been able to give AWS EKS a try with Kubebox and I've reproduced the _"Unable to verify first certificate"_ error. This is very likely due to #7, that'll help me troubleshooting it.

Besides, Kubebox needs to support the `command` field from the `user` Kube config info to rely on `aws-iam-authenticator` to authenticate and retrieve the token.

**Comment by astefanutti** [comment] 2019-01-16 18:05
The _"Unable to verify first certificate"_ error should be fixed with 792c0c8b6b9e6b65afd52a6117b54ea2b01bf49c.

I've tested Kubebox connecting successfully to EKS using the token provided by `aws-iam-authenticator token ...`.

I leave that issue open to track support for token generation and refresh with the `user.exec` field.

**Comment by berstend** [comment] 2019-01-30 14:58
Having an `Authentication failed` issue as well when starting kubebox for the first time. I'm using GKE and my regular shell session is signed in, etc.

Such a shame, just this single error message just looks absolutely gorgeous. Can't wait to try it once this is fixed. 😄

**Comment by astefanutti** [comment] 2019-01-30 15:07
@berstend It may be a different issue with GKE. If that uses OpenID connect, it should work since version 0.4.0, but apparently it doesn't so either we have an issue with OpenID connect or GKE is configured differently. Anyway, if you can retrieve a token, you should be able to use it to authenticate as a fallback.

**Comment by astefanutti** [comment] 2019-02-07 07:49
@berstend That'd be great if you could provide details about the kube config file section relevant to connecting to GKE. I would suggest you create a separate issue.

**Comment by PierreBeucher** [comment] 2019-07-10 08:58
Same issue but did not have `aws-iam-authenticator` available. I instead used 

    aws eks get-token --cluster-name [my-cluster] 

To get a token to authenticate with Kubebox

**Comment by astefanutti** [comment] 2019-08-13 19:47
It should now be supported starting version 0.6.0. Thanks for your patience!

**Closed by astefanutti** 2019-08-13 19:47 UTC
Labels: feature
